#!/usr/bin/env bash
# Spin a topic off into a FRESH Claude Code session in a new cmux split.
#
# Unlike claude-branch-split (which clones the current transcript so two
# divergent threads of the same conversation run side-by-side), this starts a
# brand-new session seeded with:
#   1. A task prompt (required, positional argument)
#   2. An optional passoff context (via stdin or 3rd argument) — the current
#      session's state summary so the spun-off session knows what's happening
#      in the parent. Generated by the /passoff skill.
#
# The passoff is appended as durable system-prompt context alongside the task,
# so both survive compaction.
#
# Usage:
#   spinoff-session.sh <task-file> [model] [passoff-file]
#   echo '<passoff>' | spinoff-session.sh <task-file> [model]
set -euo pipefail

prompt_file="${1:-}"
if [[ -z "$prompt_file" || ! -f "$prompt_file" ]]; then
  echo "usage: spinoff-session.sh <task-file> [model] [passoff-file]" >&2
  echo "       echo '<passoff>' | spinoff-session.sh <task-file> [model]" >&2
  exit 2
fi

# ── model ─────────────────────────────────────────────────────────
model="${2:-sonnet}"

# ── passoff: arg 3 > stdin ───────────────────────────────────────
passoff_file="${3:-}"  # may be empty
passoff_stdin=""
if [[ ! -t 0 ]]; then
  passoff_stdin="$(cat)"
fi

if [[ -n "$passoff_file" && ! -f "$passoff_file" ]]; then
  echo "error: passoff file not found: $passoff_file" >&2
  exit 2
fi

if [[ -n "$passoff_file" ]]; then
  passoff_missing=false
elif [[ -n "${passoff_stdin//[$'\t\r\n ']}" ]]; then
  passoff_missing=false
else
  passoff_missing=true
fi

# ── cmux guards ───────────────────────────────────────────────────
if [[ -z "${CMUX_WORKSPACE_ID:-}" ]]; then
  echo "error: not running inside a cmux terminal (CMUX_WORKSPACE_ID unset)" >&2
  exit 2
fi

if ! command -v cmux >/dev/null 2>&1; then
  echo "error: cmux CLI not found on PATH" >&2
  exit 2
fi

# ── cwd ───────────────────────────────────────────────────────────
start_dir="$(pwd)"

# Shell-safe single-quote helper.
sq() { printf "'%s'" "${1//\'/\'\\\'\'}"; }

# ── resolve cmux refs ─────────────────────────────────────────────
ident="$(cmux identify)"
caller_surface="$(printf '%s\n' "$ident" | grep -m1 '"surface_ref"'   | grep -oE 'surface:[0-9]+'   || true)"
caller_ws="$(printf '%s\n' "$ident"      | grep -m1 '"workspace_ref"' | grep -oE 'workspace:[0-9]+' || true)"
if [[ -z "$caller_surface" || -z "$caller_ws" ]]; then
  echo "error: could not resolve current cmux surface/workspace via 'cmux identify'" >&2
  exit 2
fi

# ── create new split ──────────────────────────────────────────────
split_out="$(cmux new-split down --surface "$caller_surface" --workspace "$caller_ws" --focus true)"
surface_ref="$(printf '%s\n' "$split_out" | grep -oE 'surface:[0-9]+' | grep -v "^${caller_surface}\$" | head -n1 || true)"

if [[ -z "$surface_ref" ]]; then
  echo "error: could not resolve new split surface from: $split_out" >&2
  exit 2
fi

# ── build launch script ───────────────────────────────────────────
# A POSIX-sh wrapper that cd's, forwards env, and exec's claude with
# the task + passoff as appended system-prompt context (both durable
# and compaction-resistant).
launch_script="$(mktemp "${TMPDIR:-/tmp}/claude-spinoff-launch-XXXXXX")"
{
  echo "#!/bin/sh"
  echo "cd $(sq "$start_dir") || exit 1"
  for _name in ${!CLAUDE_@} ${!ANTHROPIC_@}; do
    case "$_name" in
      CLAUDE_CODE_SESSION_ID|CLAUDE_CODE_ENTRYPOINT|CLAUDE_CODE_EXECPATH) continue ;;
    esac
    echo "export ${_name}=$(sq "${!_name}")"
  done

  passoff_flag=""
  if ! $passoff_missing; then
    # Write passoff into a temp file referenced by the launch script.
    passoff_tmp="$(mktemp "${TMPDIR:-/tmp}/claude-spinoff-passoff-XXXXXX")"
    if [[ -n "${passoff_file:-}" ]]; then
      cat "$passoff_file" > "$passoff_tmp"
    elif [[ -n "${passoff_stdin//[$'\t\r\n ']}" ]]; then
      printf '%s\n' "$passoff_stdin" > "$passoff_tmp"
    fi
    passoff_flag="--append-system-prompt-file $(sq "$passoff_tmp")"
    echo "export CLAUDE_SPINOFF_PASSOFF_FILE='${passoff_tmp}'"
  fi

  # Task prompt goes first (instructions), passoff second (context).
  # Both are --append-system-prompt-file so they live in system context,
  # not as user messages that scroll away.
  #
  # --dangerously-skip-permissions: explicit opt-in bypass so the spun-off
  # session starts without the interactive permission gate.
  if $passoff_missing; then
    echo "exec claude --dangerously-skip-permissions --model $(sq "$model") --append-system-prompt-file $(sq "$prompt_file") 'Begin the task defined in your appended instructions. Work autonomously through it to completion, then report what changed.'"
  else
    echo "exec claude --dangerously-skip-permissions --model $(sq "$model") --append-system-prompt-file $(sq "$prompt_file") ${passoff_flag} 'Begin the task defined in your appended instructions. Your appended passoff context describes the parent session state. Work autonomously through the task to completion, then report what changed.'"
  fi
} > "$launch_script"

# ── respawn with fish, then run the launch script ─────────────────
# new-split may invoke the workspace's default shell (bash/zsh/etc);
# respawn guarantees fish. Then we send the launch command.
cmux respawn-pane \
  --workspace "$caller_ws" \
  --surface "$surface_ref" \
  --command fish
sleep 1

cmd="sh $(sq "$launch_script")"
cmux send     --workspace "$caller_ws" --surface "$surface_ref" "$cmd"
cmux send-key --workspace "$caller_ws" --surface "$surface_ref" Enter

echo "spun off topic into new cmux split"
echo "model: ${model}"
echo "task: ${prompt_file}"
if ! $passoff_missing; then
  if [[ -n "$passoff_file" ]]; then
    passoff_chars="$(wc -c < "$passoff_file" | tr -d '[:space:]')"
    echo "passoff: included (${passoff_chars} chars from file)"
  else
    passoff_chars="$(printf '%s' "$passoff_stdin" | wc -c | tr -d '[:space:]')"
    echo "passoff: included (${passoff_chars} chars from stdin)"
  fi
fi
echo "shell: fish"
echo "this pane continues; the new pane runs a fresh session."
