#!/usr/bin/env bash
# Handoff current Claude Code session to a fresh one in a new cmux split.
# Takes a passoff prompt (generated by /passoff), creates a new downward
# split pane running fish, launches claude inside it, and pastes the
# passoff as the initial message so the new session knows where to pick up.
#
# Usage:
#   passoff-session.sh '<passoff-text>'
#   echo '<passoff-text>' | passoff-session.sh
set -euo pipefail

if [[ -z "${CMUX_WORKSPACE_ID:-}" ]]; then
  echo "error: not running inside a cmux terminal (CMUX_WORKSPACE_ID unset)" >&2
  exit 2
fi

if ! command -v cmux >/dev/null 2>&1; then
  echo "error: cmux CLI not found on PATH" >&2
  exit 2
fi

# ── passoff source: argument > stdin ──────────────────────────────
if [ $# -gt 0 ]; then
  passoff="$*"
elif [ ! -t 0 ]; then
  passoff="$(cat)"
fi

if [[ -z "${passoff:-}" ]]; then
  echo "usage: passoff-session.sh '<passoff-text>'" >&2
  echo "       echo '<passoff-text>' | passoff-session.sh" >&2
  exit 2
fi

# ── create new split ──────────────────────────────────────────────
echo "creating new split pane …"

split_out="$(cmux new-pane --direction down --workspace "$CMUX_WORKSPACE_ID" --focus true)"
surface_ref="$(printf '%s\n' "$split_out" | grep -oE 'surface:[0-9]+' | head -n1 || true)"

if [[ -z "$surface_ref" ]]; then
  echo "error: could not extract surface ref from: $split_out" >&2
  exit 3
fi

# ── respawn with fish as the native shell ─────────────────────────
# new-pane inherits the workspace default shell; respawn-pane lets us
# explicitly set fish so claude runs in the user's preferred shell.
cmux respawn-pane \
  --workspace "$CMUX_WORKSPACE_ID" \
  --surface "$surface_ref" \
  --command fish
sleep 1

# ── launch claude inside fish ─────────────────────────────────────
cmux send --workspace "$CMUX_WORKSPACE_ID" --surface "$surface_ref" claude
cmux send-key --workspace "$CMUX_WORKSPACE_ID" --surface "$surface_ref" Enter

echo "waiting for claude to initialize …"
sleep 5

# ── stage passoff in cmux buffer ──────────────────────────────────
# Uses Python to avoid shell escaping issues with multi-line markdown.
tmpfile="$(mktemp)"
printf '%s\n' "$passoff" > "$tmpfile"
python3 -c "
import subprocess, sys
with open('$tmpfile') as f:
    content = f.read()
subprocess.run(['cmux', 'set-buffer', '--name', 'passoff', content], check=True)
"
rm -f "$tmpfile"

# ── paste passoff as claude's first prompt ────────────────────────
cmux paste-buffer \
  --name passoff \
  --workspace "$CMUX_WORKSPACE_ID" \
  --surface "$surface_ref"

cmux send-key \
  --workspace "$CMUX_WORKSPACE_ID" \
  --surface "$surface_ref" \
  Enter

echo "done — fresh claude session launched with passoff in new split"
