// Package skillsync keeps a personal Claude Code skill in sync with every
// resolved mcx chain, so a chain is invocable as /<chain-name> without the
// user hand-writing a skill file. Skills land under the user's own
// ~/.claude/skills — never a plugin's installed cache, which the marketplace
// installer owns and can wipe or replace on any update.
package skillsync

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/emmahyde/mcx/internal/registry"
)

// managedMarker sits inside every mcx-generated skill dir so Sync only ever
// creates or removes skills it made itself; a hand-authored skill that
// happens to share a chain's name has no marker and is never touched.
const managedMarker = ".mcx-managed"

// Dir returns the personal skills directory (~/.claude/skills).
func Dir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("skillsync: resolve home dir: %w", err)
	}
	return filepath.Join(home, ".claude", "skills"), nil
}

// Sync reconciles ~/.claude/skills against chains: writes or refreshes a
// skill for every chain, and removes any mcx-managed skill whose chain no
// longer resolves. skipped lists chains whose name collides with an existing
// non-managed (hand-authored) skill dir, which Sync leaves untouched.
func Sync(chains []registry.Tool) (created, removed, skipped []string, err error) {
	dir, err := Dir()
	if err != nil {
		return nil, nil, nil, err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, nil, nil, fmt.Errorf("skillsync: create skills dir: %w", err)
	}

	wanted := make(map[string]bool, len(chains))
	for _, t := range chains {
		wanted[t.Name] = true
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("skillsync: read skills dir: %w", err)
	}
	managed := make(map[string]bool, len(entries))
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		if _, err := os.Stat(filepath.Join(dir, e.Name(), managedMarker)); err == nil {
			managed[e.Name()] = true
		}
	}

	for name := range managed {
		if wanted[name] {
			continue
		}
		if err := os.RemoveAll(filepath.Join(dir, name)); err != nil {
			return created, removed, skipped, fmt.Errorf("skillsync: remove stale skill %q: %w", name, err)
		}
		removed = append(removed, name)
	}

	for _, t := range chains {
		skillDir := filepath.Join(dir, t.Name)
		if !managed[t.Name] {
			if info, statErr := os.Stat(skillDir); statErr == nil && info.IsDir() {
				skipped = append(skipped, t.Name)
				continue
			}
		}
		if err := os.MkdirAll(skillDir, 0o755); err != nil {
			return created, removed, skipped, fmt.Errorf("skillsync: create skill dir %q: %w", t.Name, err)
		}
		if err := os.WriteFile(filepath.Join(skillDir, "SKILL.md"), []byte(render(t)), 0o644); err != nil {
			return created, removed, skipped, fmt.Errorf("skillsync: write skill %q: %w", t.Name, err)
		}
		if err := os.WriteFile(filepath.Join(skillDir, managedMarker), nil, 0o644); err != nil {
			return created, removed, skipped, fmt.Errorf("skillsync: mark skill %q: %w", t.Name, err)
		}
		if !managed[t.Name] {
			created = append(created, t.Name)
		}
	}
	return created, removed, skipped, nil
}

// render builds a generated skill's SKILL.md: frontmatter carrying the
// chain's own description (so Claude's skill matcher can trigger on it), and
// a body that always routes through `mcx run` rather than duplicating the
// chain's logic in prose.
func render(t registry.Tool) string {
	desc := strings.TrimSpace(t.Description)
	if desc == "" {
		desc = "Runs the mcx chain " + t.Name + "."
	}

	var b strings.Builder
	fmt.Fprintf(&b, "---\nname: %s\ndescription: %s\n---\n\n", t.Name, desc)
	fmt.Fprintf(&b, "Auto-generated by mcx skillsync from the %q chain; regenerated on every `mcx register`/`mcx remove`, so hand edits do not persist.\n\n", t.Name)
	fmt.Fprintf(&b, "%s\n\n", desc)
	fmt.Fprintf(&b, "Run it with the Bash tool, passing arguments as the first operand:\n\n    mcx run '{\"...\": \"...\"}' %s\n", t.Name)
	if schema := prettySchema(t.Schema); schema != "" {
		fmt.Fprintf(&b, "\nArgs schema:\n\n```json\n%s\n```\n", schema)
	}
	return b.String()
}

// prettySchema re-indents a chain's stored schema for the skill body; an
// empty or unparsable schema (the permissive default) renders as nothing.
func prettySchema(raw json.RawMessage) string {
	if len(raw) == 0 {
		return ""
	}
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		return ""
	}
	pretty, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return ""
	}
	return string(pretty)
}
